package com.plantpulse.scheduler;

import com.plantpulse.domain.Machine;
import com.plantpulse.domain.WorkOrder;
import com.plantpulse.domain.enums.MachineStatus;
import com.plantpulse.domain.enums.Priority;
import com.plantpulse.domain.enums.WorkOrderStatus;
import com.plantpulse.domain.enums.WorkOrderType;
import com.plantpulse.repository.MachineRepository;
import com.plantpulse.repository.WorkOrderRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class PreventiveMaintenanceSchedulerTest {

    @Mock
    private MachineRepository machineRepository;

    @Mock
    private WorkOrderRepository workOrderRepository;

    @InjectMocks
    private PreventiveMaintenanceScheduler scheduler;

    @Captor
    private ArgumentCaptor<WorkOrder> workOrderCaptor;

    private static final LocalDate TODAY = LocalDate.of(2026, 7, 27);

    private Machine machine;

    @BeforeEach
    void setUp() {
        machine = Machine.builder()
                .id(1L)
                .name("CNC Lathe #1")
                .type("CNC Lathe")
                .status(MachineStatus.OPERATIONAL)
                .baselineTemperature(58.0)
                .baselineVibration(2.2)
                .build();
    }

    @Test
    void noIntervalConfigured_doesNothing() {
        machine.setMaintenanceIntervalDays(null);

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        assertThat(result).isEmpty();
        verify(workOrderRepository, never()).findByMachineId(any());
        verify(workOrderRepository, never()).save(any());
    }

    @Test
    void alreadyHasOpenPreventiveOrder_doesNothing() {
        machine.setMaintenanceIntervalDays(30);
        machine.setInstallDate(TODAY.minusDays(365));
        WorkOrder openOrder = WorkOrder.builder().id(9L).type(WorkOrderType.PREVENTIVE).status(WorkOrderStatus.PENDING).build();
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of(openOrder));

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        assertThat(result).isEmpty();
        verify(workOrderRepository, never()).save(any());
    }

    @Test
    void noReferenceDateAvailable_doesNothing() {
        machine.setMaintenanceIntervalDays(30);
        machine.setInstallDate(null);
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of());

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        assertThat(result).isEmpty();
        verify(workOrderRepository, never()).save(any());
    }

    @Test
    void noPriorPreventiveOrder_usesInstallDate_dueToday_createsOrder() {
        machine.setMaintenanceIntervalDays(90);
        machine.setInstallDate(TODAY.minusDays(90));
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of());
        when(workOrderRepository.save(any(WorkOrder.class))).thenAnswer(inv -> inv.getArgument(0));

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        assertThat(result).isPresent();
        verify(workOrderRepository).save(workOrderCaptor.capture());
        WorkOrder saved = workOrderCaptor.getValue();
        assertThat(saved.getMachine()).isEqualTo(machine);
        assertThat(saved.getType()).isEqualTo(WorkOrderType.PREVENTIVE);
        assertThat(saved.getStatus()).isEqualTo(WorkOrderStatus.PENDING);
        assertThat(saved.getPriority()).isEqualTo(Priority.MEDIUM);
        assertThat(saved.isAutoGenerated()).isTrue();
        assertThat(saved.getDescription()).contains("90 days");
    }

    @Test
    void noPriorPreventiveOrder_usesInstallDate_notYetDue_doesNothing() {
        machine.setMaintenanceIntervalDays(90);
        machine.setInstallDate(TODAY.minusDays(10));
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of());

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        assertThat(result).isEmpty();
        verify(workOrderRepository, never()).save(any());
    }

    @Test
    void closedPreventiveOrderExists_usesItsClosedDateInsteadOfInstallDate() {
        machine.setMaintenanceIntervalDays(30);
        machine.setInstallDate(TODAY.minusDays(1000)); // would be very overdue if used

        WorkOrder recentlyClosed = WorkOrder.builder()
                .id(2L)
                .type(WorkOrderType.PREVENTIVE)
                .status(WorkOrderStatus.DONE)
                .closedAt(TODAY.minusDays(5).atStartOfDay(ZoneOffset.UTC).toInstant())
                .build();
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of(recentlyClosed));

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        // last preventive was only 5 days ago, interval is 30 -> not due yet
        assertThat(result).isEmpty();
        verify(workOrderRepository, never()).save(any());
    }

    @Test
    void closedPreventiveOrderExists_dueBasedOnMostRecentClosedOrder() {
        machine.setMaintenanceIntervalDays(30);

        WorkOrder olderClosed = WorkOrder.builder()
                .id(2L)
                .type(WorkOrderType.PREVENTIVE)
                .status(WorkOrderStatus.DONE)
                .closedAt(TODAY.minusDays(200).atStartOfDay(ZoneOffset.UTC).toInstant())
                .build();
        WorkOrder mostRecentClosed = WorkOrder.builder()
                .id(3L)
                .type(WorkOrderType.PREVENTIVE)
                .status(WorkOrderStatus.DONE)
                .closedAt(TODAY.minusDays(40).atStartOfDay(ZoneOffset.UTC).toInstant())
                .build();
        when(workOrderRepository.findByMachineId(1L)).thenReturn(List.of(olderClosed, mostRecentClosed));
        when(workOrderRepository.save(any(WorkOrder.class))).thenAnswer(inv -> inv.getArgument(0));

        Optional<WorkOrder> result = scheduler.evaluateMachine(machine, TODAY);

        // most recent closed preventive was 40 days ago, interval 30 -> overdue
        assertThat(result).isPresent();
    }

    @Test
    void checkDueMaintenance_evaluatesEveryMachineReturnedByRepository() {
        machine.setMaintenanceIntervalDays(30);
        machine.setInstallDate(TODAY.minusDays(365));
        Machine other = Machine.builder().id(2L).name("Press").type("Press").status(MachineStatus.OPERATIONAL)
                .baselineTemperature(60.0).baselineVibration(2.0).maintenanceIntervalDays(30)
                .installDate(TODAY.minusDays(365)).build();
        when(machineRepository.findAll()).thenReturn(List.of(machine, other));
        when(workOrderRepository.findByMachineId(any())).thenReturn(List.of());
        when(workOrderRepository.save(any(WorkOrder.class))).thenAnswer(inv -> inv.getArgument(0));

        scheduler.checkDueMaintenance();

        verify(workOrderRepository).findByMachineId(1L);
        verify(workOrderRepository).findByMachineId(2L);
    }
}
