package com.plantpulse.domain;

import com.plantpulse.domain.enums.Priority;
import com.plantpulse.domain.enums.WorkOrderStatus;
import com.plantpulse.domain.enums.WorkOrderType;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Entity
@Table(name = "work_orders")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class WorkOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @ManyToOne(optional = false)
    @JoinColumn(name = "machine_id", nullable = false)
    private Machine machine;

    @ManyToOne
    @JoinColumn(name = "technician_id")
    private Technician technician;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private WorkOrderType type;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private WorkOrderStatus status = WorkOrderStatus.PENDING;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Priority priority = Priority.MEDIUM;

    @NotBlank
    @Column(nullable = false)
    private String description;

    @Builder.Default
    private Instant createdAt = Instant.now();

    private Instant closedAt;

    /** True when this work order was opened automatically by an alert, not by a human. */
    @Builder.Default
    private boolean autoGenerated = false;
}
