package com.plantpulse.service;

import com.plantpulse.domain.Machine;
import com.plantpulse.domain.WorkOrder;
import com.plantpulse.domain.enums.Priority;
import com.plantpulse.domain.enums.WorkOrderStatus;
import com.plantpulse.domain.enums.WorkOrderType;
import com.plantpulse.exception.ResourceNotFoundException;
import com.plantpulse.repository.WorkOrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;

@Service
@RequiredArgsConstructor
public class WorkOrderService {

    private final WorkOrderRepository workOrderRepository;

    public List<WorkOrder> findAll() {
        return workOrderRepository.findAll();
    }

    public WorkOrder create(WorkOrder workOrder) {
        return workOrderRepository.save(workOrder);
    }

    public WorkOrder updateStatus(Long id, WorkOrderStatus status) {
        WorkOrder order = workOrderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Work order not found: " + id));
        order.setStatus(status);
        if (status == WorkOrderStatus.DONE) {
            order.setClosedAt(Instant.now());
        }
        return workOrderRepository.save(order);
    }

    /**
     * Called by the telemetry simulator when a critical threshold is breached.
     * Avoids opening duplicate corrective orders for the same machine while
     * one is already pending or in progress.
     */
    public WorkOrder openAutoCorrectiveOrder(Machine machine, String reason) {
        boolean alreadyOpen = workOrderRepository.findByMachineId(machine.getId()).stream()
                .anyMatch(wo -> wo.isAutoGenerated() && wo.getStatus() != WorkOrderStatus.DONE);

        if (alreadyOpen) {
            return null;
        }

        WorkOrder order = WorkOrder.builder()
                .machine(machine)
                .type(WorkOrderType.CORRECTIVE)
                .status(WorkOrderStatus.PENDING)
                .priority(Priority.CRITICAL)
                .description("Auto-generated from sensor alert: " + reason)
                .autoGenerated(true)
                .build();

        return workOrderRepository.save(order);
    }
}
