package com.plantpulse.service;

import com.plantpulse.domain.Machine;
import com.plantpulse.domain.User;
import com.plantpulse.domain.WorkOrder;
import com.plantpulse.domain.enums.Priority;
import com.plantpulse.domain.enums.Role;
import com.plantpulse.domain.enums.WorkOrderStatus;
import com.plantpulse.domain.enums.WorkOrderType;
import com.plantpulse.exception.ResourceNotFoundException;
import com.plantpulse.repository.WorkOrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;

@Service
@RequiredArgsConstructor
public class WorkOrderService {

    private final WorkOrderRepository workOrderRepository;

    /** ADMIN sees every work order; TECHNICIAN sees only the ones assigned to their linked Technician record. */
    public List<WorkOrder> findAllVisibleTo(User currentUser) {
        if (currentUser.getRole() == Role.ADMIN) {
            return workOrderRepository.findAll();
        }
        return workOrderRepository.findByTechnicianId(currentUser.getTechnician().getId());
    }

    public WorkOrder create(WorkOrder workOrder) {
        return workOrderRepository.save(workOrder);
    }

    public WorkOrder updateStatus(Long id, WorkOrderStatus status, User currentUser) {
        WorkOrder order = workOrderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Work order not found: " + id));

        if (currentUser.getRole() == Role.TECHNICIAN && !isAssignedTo(order, currentUser)) {
            throw new AccessDeniedException("Not assigned to this work order");
        }

        order.setStatus(status);
        if (status == WorkOrderStatus.DONE) {
            order.setClosedAt(Instant.now());
        }
        return workOrderRepository.save(order);
    }

    private boolean isAssignedTo(WorkOrder order, User currentUser) {
        return order.getTechnician() != null
                && currentUser.getTechnician() != null
                && order.getTechnician().getId().equals(currentUser.getTechnician().getId());
    }

    /**
     * Called by the telemetry simulator when a critical threshold is breached.
     * Avoids opening duplicate corrective orders for the same machine while
     * one is already pending or in progress.
     */
    public WorkOrder openAutoCorrectiveOrder(Machine machine, String reason) {
        boolean alreadyOpen = workOrderRepository.findByMachineId(machine.getId()).stream()
                .anyMatch(wo -> wo.isAutoGenerated() && wo.getStatus() != WorkOrderStatus.DONE);

        if (alreadyOpen) {
            return null;
        }

        WorkOrder order = WorkOrder.builder()
                .machine(machine)
                .type(WorkOrderType.CORRECTIVE)
                .status(WorkOrderStatus.PENDING)
                .priority(Priority.CRITICAL)
                .description("Auto-generated from sensor alert: " + reason)
                .autoGenerated(true)
                .build();

        return workOrderRepository.save(order);
    }
}
