package com.plantpulse.scheduler;

import com.plantpulse.domain.Machine;
import com.plantpulse.domain.WorkOrder;
import com.plantpulse.domain.enums.Priority;
import com.plantpulse.domain.enums.WorkOrderStatus;
import com.plantpulse.domain.enums.WorkOrderType;
import com.plantpulse.repository.MachineRepository;
import com.plantpulse.repository.WorkOrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

/**
 * Opens a PREVENTIVE work order when a machine's maintenance interval has
 * elapsed since its last closed preventive visit — or, if it has never had
 * one, since its install date. Calendar-day granularity only; scheduling by
 * machine run-hours is out of scope.
 *
 * Polls fairly often (see plantpulse.preventive-maintenance.check-interval-ms)
 * even though the underlying condition only changes once a day, the same
 * demo-friendliness tradeoff TelemetrySimulatorService makes — a reviewer
 * shouldn't have to wait a real day to see this feature fire.
 */
@Component
@RequiredArgsConstructor
public class PreventiveMaintenanceScheduler {

    private final MachineRepository machineRepository;
    private final WorkOrderRepository workOrderRepository;

    @Scheduled(fixedRateString = "${plantpulse.preventive-maintenance.check-interval-ms:60000}")
    public void checkDueMaintenance() {
        LocalDate today = LocalDate.now();
        for (Machine machine : machineRepository.findAll()) {
            evaluateMachine(machine, today);
        }
    }

    /**
     * Avoids opening a duplicate preventive order while one is already
     * pending/in-progress, mirroring WorkOrderService.openAutoCorrectiveOrder.
     */
    Optional<WorkOrder> evaluateMachine(Machine machine, LocalDate today) {
        if (machine.getMaintenanceIntervalDays() == null) {
            return Optional.empty();
        }

        List<WorkOrder> machineOrders = workOrderRepository.findByMachineId(machine.getId());

        boolean alreadyScheduled = machineOrders.stream()
                .anyMatch(wo -> wo.getType() == WorkOrderType.PREVENTIVE && wo.getStatus() != WorkOrderStatus.DONE);
        if (alreadyScheduled) {
            return Optional.empty();
        }

        LocalDate reference = machineOrders.stream()
                .filter(wo -> wo.getType() == WorkOrderType.PREVENTIVE
                        && wo.getStatus() == WorkOrderStatus.DONE
                        && wo.getClosedAt() != null)
                .map(wo -> wo.getClosedAt().atZone(ZoneOffset.UTC).toLocalDate())
                .max(Comparator.naturalOrder())
                .orElse(machine.getInstallDate());

        if (reference == null) {
            return Optional.empty();
        }

        LocalDate dueDate = reference.plusDays(machine.getMaintenanceIntervalDays());
        if (today.isBefore(dueDate)) {
            return Optional.empty();
        }

        WorkOrder order = WorkOrder.builder()
                .machine(machine)
                .type(WorkOrderType.PREVENTIVE)
                .status(WorkOrderStatus.PENDING)
                .priority(Priority.MEDIUM)
                .description("Scheduled preventive maintenance (every %d days)".formatted(machine.getMaintenanceIntervalDays()))
                .autoGenerated(true)
                .build();

        return Optional.of(workOrderRepository.save(order));
    }
}
