export type MachineStatus = 'OPERATIONAL' | 'DOWN' | 'MAINTENANCE';
export type AlertSeverity = 'WARNING' | 'CRITICAL';
export type WorkOrderStatus = 'PENDING' | 'IN_PROGRESS' | 'DONE';
export type WorkOrderType = 'PREVENTIVE' | 'CORRECTIVE';
export type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type Role = 'ADMIN' | 'TECHNICIAN';

export interface LoginResponse {
  token: string;
  email: string;
  role: Role;
}

export interface Machine {
  id: number;
  name: string;
  type: string;
  location: string;
  status: MachineStatus;
  baselineTemperature: number;
  baselineVibration: number;
  installDate: string | null;
  maintenanceIntervalDays: number | null;
}

export interface TelemetryMessage {
  machineId: number;
  machineName: string;
  temperature: number;
  vibration: number;
  rpm: number;
  timestamp: string;
}

export interface AlertMessage {
  alertId: number;
  machineId: number;
  machineName: string;
  severity: AlertSeverity;
  message: string;
  linkedWorkOrderId: number | null;
  timestamp: string;
}

export interface WorkOrder {
  id: number;
  machine: Machine;
  type: WorkOrderType;
  status: WorkOrderStatus;
  priority: Priority;
  description: string;
  createdAt: string;
  autoGenerated: boolean;
}

export interface SparePart {
  id: number;
  name: string;
  stockQuantity: number;
  minStockThreshold: number;
  unitCost: number | null;
}
